# Generated by Django 3.0.14 on 2022-03-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
